---
- name: Install docker
  hosts: demo
  become: yes
  tasks:
  - name: Run a nginx container
    docker_container:
      name: nginx-image
      image: dvp1/nginxtest:9

      state: started
      recreate: yes
      exposed_ports:
       - 8080:80
      tty: true
      detach: true
